name: Lock and unlock main branch
on: workflow_dispatch

jobs:
  get-branch-protection:
    runs-on: ubuntu-latest
    steps:
      - name: get branch protection with GitHub API
        run: |
          curl \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/AnqiPang/homebrew-tap/branches/main/protection

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
